image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  
stages:
  - Test

flake8:
  stage: Test
  allow_failure: true
  script:
  - flake8 --max-line-length=120
  
pytest:
  stage: Test
  script:
  - pytest --cov --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml