image: "python:3.7"

before_script:
  - python --version
  - pip install flake8
  - pip install tox

stages:
  - Lint
  - Test

flake8:
  stage: Lint
  allow_failure: true
  script:
  - flake8
  
pytest:
  stage: Test
  script:
  - tox
