image: "python:3.7"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

before_script:
  - pip install flake8
  - pip install tox

cache:
  key: one-key-to-rule-them-all
  paths:
  - .cache
  - .tox

lint:
  allow_failure: true
  script:
  - flake8
  
pytest:
  script:
  - tox
  artifacts:
    reports:
      junit: report.xml

benchmark:
  when: manual
  script:
    - tox -e benchmark -q
